import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

live_config_reload = true

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
