#!/bin/zsh

echo "Bootstrapping host..."

.bin/ensure-symbolic-links
.bin/generate-grconfig

if [[ ! -d ~/.oh-my-zsh ]] ; then
  echo "fatal: You have to install oh-my-zsh."
  exit 1
fi

if [[ ! -d ~/.oh-my-zsh/custom/plugins/zshmarks ]] ; then
  git clone https://github.com/jocelynmallon/zshmarks.git ~/.oh-my-zsh/custom/plugins/zshmarks
fi

set-bookmark-defaults

chmod 700 $HOME/.ssh
chmod 600 $HOME/.ssh/config

test -d ~/.vim/bundle/Vundle.vim || git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Done."
