#!/bin/zsh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "$HOME/.Xmodmap"

#~/.bin/reset-audio &
#~/.bin/start-synergy &
#fbsetroot -solid \#E1FFC0 &
#xmodmap ~/.Xmodmap &

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/tux/.fluxbox/log"

fbsetroot -solid \#2b2b2b &

exec fluxbox &
fbpid=$!
  
sleep 1
{
  update-time &

  # Applications you want to run after fluxbox has started
  # MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN & AT THE END.
  xrdb ~/.Xdefaults &
  xset dpms 0 0 0 &
  xset s off &

  restart-vbox-client &

  # Macbook Pro 2016 size
  xrandr --size 1680x1050 &

  {sleep 7 && cp ~/.configs/gtkrc-2.0 ~/.gtkrc-2.0} &

  #display-mode no-monitor && launch-development-environment 3 &
  #{sleep 5 && display-mode no-monitor} &
} &
 
wait $fbpid

