#!/bin/zsh

fbsetroot -solid \#000000 &

exec fluxbox &
fbpid=$!

sleep 1
{
  update-time &

  # Applications you want to run after fluxbox has started
  # MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN & AT THE END.
  xrdb ~/.Xdefaults &
  xset dpms 0 0 0 &
  xset s off &

  xmodmap ~/.Xmodmap &

  case $HOST in
    server)
      xrandr -s 1280x720 &
      ;;
    *)
      ;;
  esac

  #display-mode no-monitor && launch-development-environment 3 &
  #{sleep 5 && display-mode no-monitor} &
} &

wait $fbpid

