# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          # format: "%m/%d/%Y"
          format: "%Y-%m-%d"
  # uuidgen
  - trigger: ":uuid"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "uuidgen"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # ----------------------------------------------
  - trigger: ":mb-daily-title"
    vars:
      - name: mbdate
        type: date
        params:
          format: "%Y-%m-%d"
    replace: "MapBlocks / Updates / Daily - {{mbdate}}"

  - trigger: ":mb-updates"
    vars:
      - name: mbdate
        type: date
        params:
          format: "%Y-%m-%d"
    replace: |
      # MapBlocks / Updates / Daily / {{mbdate}}

      `{{mbdate}}-daily.md`

      ---

      ## GitHub Issues on {{mbdate}}

      - [Updated](https://github.com/mapblocks/microservices/issues?q=updated%3A{{mbdate}})
      [Closed](https://github.com/mapblocks/microservices/issues?q=closed%3A{{mbdate}})

      ---

      ## Summary



      ## Notes

  # ----------------------------------------------
  - trigger: ":greet"
    form: |
      Hey {{name}},
      {{text}}
      Happy Birthday!
    form_fields:
      text:
        multiline: true
