session_name: configs
windows:
- window_name: edit
  shell_command_before:
    - cd ~/.configs
    - sw
  panes:
    - null
- window_name: aux-0
  layout: even-horizontal
  shell_command_before:
    - cd ~/.configs
  panes:
    - null
    - null
- window_name: aux-1
  layout: even-horizontal
  shell_command_before:
    - cd ~/.configs
  panes:
    - null
    - null
