#!/bin/zsh

_current_script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ------------------------------------------------
# UTILITY ----------------------------------------
# ------------------------------------------------
function _ensure_symbolic_link() {
  if [[ $1 == "--sudo" ]] ; then
    _sudo=true
    shift
  else
    _sudo=false
  fi

  _source="$HOME/.configs/$1"
  _destination=$2

  echo "Linking: $source -> $_destination"

  if ! test -e $_source; then
    echo "fatal: Source '$_source' does not exist."
    exit 1
  fi

  # If the symbolic link already exists, remove
  # it and recreate.
  if test -L $_destination; then
    if ( $_sudo ); then
      sudo rm $_destination
    else
      rm $_destination
    fi
  fi

  if test -d $_source && test -d $_destination; then
    echo "fatal: Destination '$_destination' is a directory and already exists."
    exit 1
  fi

  if test -f $_source && test -f $_destination; then
    echo "fatal: Destination '$_destination' is a file and already exists."
    exit 1
  fi

  # If our destination is a directory, ensure the
  # paths so we can create the symlink within
  # them.
  # if test -d $_destination; then
  #   test -d `dirname $_destination` || mkdir -p `dirname $_destination`
  # fi

  if ( $_sudo ); then
    sudo ln -s $_source $_destination
  else
    ln -s $_source $_destination
  fi
}

# ------------------------------------------------
# ZSH --------------------------------------------
# ------------------------------------------------
test -d ~/.config || mkdir ~/.config

# Zsh
# ------------------------------------------------
_ensure_symbolic_link zshrc ~/.zshrc

test -d /etc/zsh || sudo mkdir /etc/zsh
_ensure_symbolic_link --sudo etc/zsh/shared /etc/zsh/shared
_ensure_symbolic_link --sudo etc/zsh/colors /etc/zsh/colors

# ------------------------------------------------
_ensure_symbolic_link audio ~/.audio

# ------------------------------------------------
# VIM --------------------------------------------
# ------------------------------------------------
_ensure_symbolic_link vim   ~/.vim
_ensure_symbolic_link vim   ~/.config/nvim
_ensure_symbolic_link vimrc ~/.vimrc
_ensure_symbolic_link vimrc ~/.config/nvim/init.vim
_ensure_symbolic_link htop  ~/.config/htop

# ------------------------------------------------
# OTHER ------------------------------------------
# ------------------------------------------------
_ensure_symbolic_link tmux.conf ~/.tmux.conf

