#!/bin/zsh

# -----------------------------------------------
# TRANSMISSION ----------------------------------
# -----------------------------------------------
_transmission_daemon_dir="/var/lib/transmission-daemon/info"
_transmission_daemon_path="$_transmission_daemon_dir/settings.json"

if test -d $_transmission_daemon_dir; then
  if ! test -h $_transmission_daemon_path; then
    mv $_transmission_daemon_path $_transmission_daemon_path.backup
    ln -s $1/transmission-daemon-settings.json $_transmission_daemon_path
  fi
fi
