# Cloudflare WARP Configuration
# Location: ~/.cloudflare/warp.yaml or /etc/cloudflare-warp/warp.yaml

# Organization and authentication settings
organizations:
  - id: "your-org-id"  # Replace with your actual organization ID
    name: "Your Organization Name"
    auth_domain: "your-domain.cloudflareaccess.com"

# Client configuration
client:
  # Basic settings
  mtu: 1420
  keepalive: 25
  
  # Connection settings
  peers:
    - public_key: "your-public-key"  # Replace with your actual public key
      endpoint: "engage.cloudflareclient.com:2408"
      allowed_ips:
        - "0.0.0.0/0"
        - "::/0"

  # DNS settings
  dns:
    upstream:
      - "1.1.1.1"  # Cloudflare's primary DNS
      - "1.0.0.1"  # Cloudflare's secondary DNS
    fallback:
      - "8.8.8.8"  # Google DNS as fallback
    
  # Split tunnel configuration
  # Routes all traffic through WARP except specified domains/IPs
  split_tunnel:
    exclude:
      domains:
        - "internal.example.com"
        - "*.local"
      ips:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

  # Proxy settings (if needed)
  proxy:
    enable: false
    # http: "http://proxy.example.com:3128"
    # https: "https://proxy.example.com:3128"

  # Logging configuration
  logging:
    level: "info"  # Options: debug, info, warn, error
    file: "/var/log/cloudflare-warp/warp.log"

  # Interface settings
  interface:
    name: "warp0"
    addresses:
      - "auto"  # Automatically assign IP address

  # Application settings
  app:
    allow_updates: true
    auto_connect: true
    notify: true
    captive_portal: true

# Advanced settings
advanced:
  max_connections: 5
  routing_mode: "tunnel"  # Options: tunnel, split
  disable_auto_fallback: false
  fallback_domains:
    - "example.com"
    - "*.example.net"