-- return {
--   -- Treesitter
--   {
--     "nvim-treesitter/nvim-treesitter",
--     event = { "BufReadPost", "BufNewFile" },
--     build = ":TSUpdate",
--     config = function()
--       require("plugins.coding.treesitter")
--     end,
--     dependencies = {
--       "nvim-treesitter/nvim-treesitter-textobjects",
--     },
--   },
--
--   -- Auto pairs
--   {
--     "windwp/nvim-autopairs",
--     event = "InsertEnter",
--     config = true,
--   },
--
--   -- Commenting
--   {
--     "numToStr/Comment.nvim",
--     event = { "BufReadPost", "BufNewFile" },
--     config = true,
--   },
--
--   -- Surround
--   {
--     "kylechui/nvim-surround",
--     event = { "BufReadPost", "BufNewFile" },
--     config = true,
--   },
--
--   -- Git
--   {
--     "tpope/vim-fugitive",
--     cmd = { "Git", "Gstatus", "Gblame", "Gpush", "Gpull" },
--   },
--
--   -- GitHub Copilot
--   {
--     "github/copilot.vim",
--     event = "InsertEnter",
--   },
--
--   -- Markdown preview
--   {
--     "iamcco/markdown-preview.nvim",
--     build = function()
--       vim.fn["mkdp#util#install"]()
--     end,
--     ft = "markdown",
--   },
-- }
